library(dplyr)

# 1. Merge the training and the test sets to create one data set.

testDataX <- read.table("./test/X_test.txt")
testDataY <- read.table("./test/y_test.txt")
testSubjects <- read.table("./test/subject_test.txt")
trainDataX <- read.table("./train/X_train.txt")
trainDataY <- read.table("./train/y_train.txt")
trainSubjects <- read.table("./train/subject_train.txt")
testDataY<-rename(testDataY,Activity=V1)
trainDataY<-rename(trainDataY,Activity=V1)
testSubjects <- rename(testSubjects,SubjectID=V1)
trainSubjects <- rename(trainSubjects,SubjectID=V1)
                      
testData <- cbind(testSubjects,testDataY,testDataX)
trainData <- cbind(trainSubjects,trainDataY,trainDataX)

allData <- rbind(testData,trainData)

# 2. Extract only the measurements on the mean and standard deviation for each measurement. 

features <- read.table("./features.txt")
requiredFeatures <- filter(features, grepl("mean()|std()",V2)) %>% select (V1)
requiredFeatures <- mutate(requiredFeatures, V1=paste("V",V1,sep=""))
selectedFeatures <- lapply(requiredFeatures,print)
subjectsandactivities <- select(allData,SubjectID,Activity)
meansandstds <- select(allData, one_of(selectedFeatures$V1))
selectedData <- cbind(subjectsandactivities,meansandstds)

# 3. Use descriptive activity names to name the activities in the data set
activities <- read.table('./activity_labels.txt')
activities <- rename(activities,Activity=V1,ActivityDescription = V2)
mergedData <- merge(selectedData,activities)

# 4. Appropriately label the data set with descriptive variable names. 
lookupFrame <- mutate(filter(features, grepl("mean|std",V2)),Lookup=paste("V",V1,sep="") )
colname <- filter(lookupFrame,grepl("V2$",Lookup)) %>% select(V2)

# Use the following code to regenerate the renaming commands if the data changes
# Then paste over the below commands
## renameVars <- vector()
## lapply(lookupFrame, renameVars <- print(paste("mergedData <- rename(mergedData,'",lookupFrame$V2,"'=",lookupFrame$Lookup,")",sep="" ),quote=FALSE ) )

mergedData <- rename(mergedData,'tBodyAcc-mean()-X'=V1)               
mergedData <- rename(mergedData,'tBodyAcc-mean()-Y'=V2)                
mergedData <- rename(mergedData,'tBodyAcc-mean()-Z'=V3)                
mergedData <- rename(mergedData,'tBodyAcc-std()-X'=V4)                 
mergedData <- rename(mergedData,'tBodyAcc-std()-Y'=V5)                 
mergedData <- rename(mergedData,'tBodyAcc-std()-Z'=V6)                 
mergedData <- rename(mergedData,'tGravityAcc-mean()-X'=V41)            
mergedData <- rename(mergedData,'tGravityAcc-mean()-Y'=V42)            
mergedData <- rename(mergedData,'tGravityAcc-mean()-Z'=V43)            
mergedData <- rename(mergedData,'tGravityAcc-std()-X'=V44)             
mergedData <- rename(mergedData,'tGravityAcc-std()-Y'=V45)             
mergedData <- rename(mergedData,'tGravityAcc-std()-Z'=V46)            
mergedData <- rename(mergedData,'tBodyAccJerk-mean()-X'=V81)           
mergedData <- rename(mergedData,'tBodyAccJerk-mean()-Y'=V82)           
mergedData <- rename(mergedData,'tBodyAccJerk-mean()-Z'=V83)           
mergedData <- rename(mergedData,'tBodyAccJerk-std()-X'=V84)            
mergedData <- rename(mergedData,'tBodyAccJerk-std()-Y'=V85)            
mergedData <- rename(mergedData,'tBodyAccJerk-std()-Z'=V86)            
mergedData <- rename(mergedData,'tBodyGyro-mean()-X'=V121)             
mergedData <- rename(mergedData,'tBodyGyro-mean()-Y'=V122)             
mergedData <- rename(mergedData,'tBodyGyro-mean()-Z'=V123)             
mergedData <- rename(mergedData,'tBodyGyro-std()-X'=V124)              
mergedData <- rename(mergedData,'tBodyGyro-std()-Y'=V125)              
mergedData <- rename(mergedData,'tBodyGyro-std()-Z'=V126)              
mergedData <- rename(mergedData,'tBodyGyroJerk-mean()-X'=V161)         
mergedData <- rename(mergedData,'tBodyGyroJerk-mean()-Y'=V162)         
mergedData <- rename(mergedData,'tBodyGyroJerk-mean()-Z'=V163)         
mergedData <- rename(mergedData,'tBodyGyroJerk-std()-X'=V164)          
mergedData <- rename(mergedData,'tBodyGyroJerk-std()-Y'=V165)          
mergedData <- rename(mergedData,'tBodyGyroJerk-std()-Z'=V166)          
mergedData <- rename(mergedData,'tBodyAccMag-mean()'=V201)             
mergedData <- rename(mergedData,'tBodyAccMag-std()'=V202)              
mergedData <- rename(mergedData,'tGravityAccMag-mean()'=V214)          
mergedData <- rename(mergedData,'tGravityAccMag-std()'=V215)           
mergedData <- rename(mergedData,'tBodyAccJerkMag-mean()'=V227)         
mergedData <- rename(mergedData,'tBodyAccJerkMag-std()'=V228)          
mergedData <- rename(mergedData,'tBodyGyroMag-mean()'=V240)            
mergedData <- rename(mergedData,'tBodyGyroMag-std()'=V241)             
mergedData <- rename(mergedData,'tBodyGyroJerkMag-mean()'=V253)        
mergedData <- rename(mergedData,'tBodyGyroJerkMag-std()'=V254)         
mergedData <- rename(mergedData,'fBodyAcc-mean()-X'=V266)              
mergedData <- rename(mergedData,'fBodyAcc-mean()-Y'=V267)              
mergedData <- rename(mergedData,'fBodyAcc-mean()-Z'=V268)              
mergedData <- rename(mergedData,'fBodyAcc-std()-X'=V269)               
mergedData <- rename(mergedData,'fBodyAcc-std()-Y'=V270)               
mergedData <- rename(mergedData,'fBodyAcc-std()-Z'=V271)               
mergedData <- rename(mergedData,'fBodyAcc-meanFreq()-X'=V294)          
mergedData <- rename(mergedData,'fBodyAcc-meanFreq()-Y'=V295)          
mergedData <- rename(mergedData,'fBodyAcc-meanFreq()-Z'=V296)          
mergedData <- rename(mergedData,'fBodyAccJerk-mean()-X'=V345)          
mergedData <- rename(mergedData,'fBodyAccJerk-mean()-Y'=V346)          
mergedData <- rename(mergedData,'fBodyAccJerk-mean()-Z'=V347)          
mergedData <- rename(mergedData,'fBodyAccJerk-std()-X'=V348)           
mergedData <- rename(mergedData,'fBodyAccJerk-std()-Y'=V349)           
mergedData <- rename(mergedData,'fBodyAccJerk-std()-Z'=V350)           
mergedData <- rename(mergedData,'fBodyAccJerk-meanFreq()-X'=V373)      
mergedData <- rename(mergedData,'fBodyAccJerk-meanFreq()-Y'=V374)      
mergedData <- rename(mergedData,'fBodyAccJerk-meanFreq()-Z'=V375)      
mergedData <- rename(mergedData,'fBodyGyro-mean()-X'=V424)             
mergedData <- rename(mergedData,'fBodyGyro-mean()-Y'=V425)             
mergedData <- rename(mergedData,'fBodyGyro-mean()-Z'=V426)             
mergedData <- rename(mergedData,'fBodyGyro-std()-X'=V427)              
mergedData <- rename(mergedData,'fBodyGyro-std()-Y'=V428)              
mergedData <- rename(mergedData,'fBodyGyro-std()-Z'=V429)              
mergedData <- rename(mergedData,'fBodyGyro-meanFreq()-X'=V452)         
mergedData <- rename(mergedData,'fBodyGyro-meanFreq()-Y'=V453)         
mergedData <- rename(mergedData,'fBodyGyro-meanFreq()-Z'=V454)         
mergedData <- rename(mergedData,'fBodyAccMag-mean()'=V503)             
mergedData <- rename(mergedData,'fBodyAccMag-std()'=V504)              
mergedData <- rename(mergedData,'fBodyAccMag-meanFreq()'=V513)         
mergedData <- rename(mergedData,'fBodyBodyAccJerkMag-mean()'=V516)     
mergedData <- rename(mergedData,'fBodyBodyAccJerkMag-std()'=V517)      
mergedData <- rename(mergedData,'fBodyBodyAccJerkMag-meanFreq()'=V526) 
mergedData <- rename(mergedData,'fBodyBodyGyroMag-mean()'=V529)        
mergedData <- rename(mergedData,'fBodyBodyGyroMag-std()'=V530)         
mergedData <- rename(mergedData,'fBodyBodyGyroMag-meanFreq()'=V539)    
mergedData <- rename(mergedData,'fBodyBodyGyroJerkMag-mean()'=V542)    
mergedData <- rename(mergedData,'fBodyBodyGyroJerkMag-std()'=V543)     
mergedData <- rename(mergedData,'fBodyBodyGyroJerkMag-meanFreq()'=V552)


# 5. From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject.
